server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruitmarket
    username: thang
    password: "271004"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true



