
# #
# spring.datasource.url= jdbc:mysql://localhost:3306/fruitmarket
# spring.datasource.username= thang
# spring.datasource.password= 271004
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# #
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
# spring.jpa.hibernate.ddl-auto=update

# #
# spring.resources.static-locations=classpath:/static/
# spring.thymeleaf.prefix=classpath:/templates/
# spring.thymeleaf.suffix=.html
# spring.thymeleaf.encoding=UTF-8
# spring.thymeleaf.servlet.content-type=text/html; charset=utf-8
server:
  error:
    include-message: always
    include-binding-errors: always

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/fruitmarket
    username: thang
    password: "271004"
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true



